// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lotterychain/lottery/lottery.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Lottery struct {
	TxCounter     uint64     `protobuf:"varint,1,opt,name=txCounter,proto3" json:"txCounter,omitempty"`
	TotalFees     types.Coin `protobuf:"bytes,2,opt,name=totalFees,proto3" json:"totalFees"`
	TotalBets     types.Coin `protobuf:"bytes,3,opt,name=totalBets,proto3" json:"totalBets"`
	CurrentMinBet types.Coin `protobuf:"bytes,4,opt,name=currentMinBet,proto3" json:"currentMinBet"`
	CurrentMaxBet types.Coin `protobuf:"bytes,5,opt,name=currentMaxBet,proto3" json:"currentMaxBet"`
	TxDataAll     string     `protobuf:"bytes,6,opt,name=txDataAll,proto3" json:"txDataAll,omitempty"`
}

func (m *Lottery) Reset()         { *m = Lottery{} }
func (m *Lottery) String() string { return proto.CompactTextString(m) }
func (*Lottery) ProtoMessage()    {}
func (*Lottery) Descriptor() ([]byte, []int) {
	return fileDescriptor_abdd2f1f6effb39a, []int{0}
}
func (m *Lottery) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Lottery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Lottery.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Lottery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lottery.Merge(m, src)
}
func (m *Lottery) XXX_Size() int {
	return m.Size()
}
func (m *Lottery) XXX_DiscardUnknown() {
	xxx_messageInfo_Lottery.DiscardUnknown(m)
}

var xxx_messageInfo_Lottery proto.InternalMessageInfo

func (m *Lottery) GetTxCounter() uint64 {
	if m != nil {
		return m.TxCounter
	}
	return 0
}

func (m *Lottery) GetTotalFees() types.Coin {
	if m != nil {
		return m.TotalFees
	}
	return types.Coin{}
}

func (m *Lottery) GetTotalBets() types.Coin {
	if m != nil {
		return m.TotalBets
	}
	return types.Coin{}
}

func (m *Lottery) GetCurrentMinBet() types.Coin {
	if m != nil {
		return m.CurrentMinBet
	}
	return types.Coin{}
}

func (m *Lottery) GetCurrentMaxBet() types.Coin {
	if m != nil {
		return m.CurrentMaxBet
	}
	return types.Coin{}
}

func (m *Lottery) GetTxDataAll() string {
	if m != nil {
		return m.TxDataAll
	}
	return ""
}

func init() {
	proto.RegisterType((*Lottery)(nil), "lotterychain.lottery.Lottery")
}

func init() {
	proto.RegisterFile("lotterychain/lottery/lottery.proto", fileDescriptor_abdd2f1f6effb39a)
}

var fileDescriptor_abdd2f1f6effb39a = []byte{
	// 283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0xca, 0xc9, 0x2f, 0x29,
	0x49, 0x2d, 0xaa, 0x4c, 0xce, 0x48, 0xcc, 0xcc, 0xd3, 0x87, 0x72, 0x60, 0xb4, 0x5e, 0x41, 0x51,
	0x7e, 0x49, 0xbe, 0x90, 0x08, 0xb2, 0x1a, 0x3d, 0x28, 0x47, 0x4a, 0x24, 0x3d, 0x3f, 0x3d, 0x1f,
	0xac, 0x40, 0x1f, 0xc4, 0x82, 0xa8, 0x95, 0x92, 0x4b, 0xce, 0x2f, 0xce, 0xcd, 0x2f, 0xd6, 0x4f,
	0x4a, 0x2c, 0x4e, 0xd5, 0x2f, 0x33, 0x4c, 0x4a, 0x2d, 0x49, 0x34, 0xd4, 0x4f, 0xce, 0xcf, 0xcc,
	0x83, 0xc8, 0x2b, 0x5d, 0x64, 0xe2, 0x62, 0xf7, 0x81, 0x98, 0x20, 0x24, 0xc3, 0xc5, 0x59, 0x52,
	0xe1, 0x9c, 0x5f, 0x9a, 0x57, 0x92, 0x5a, 0x24, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x12, 0x84, 0x10,
	0x10, 0xb2, 0xe5, 0xe2, 0x2c, 0xc9, 0x2f, 0x49, 0xcc, 0x71, 0x4b, 0x4d, 0x2d, 0x96, 0x60, 0x52,
	0x60, 0xd4, 0xe0, 0x36, 0x92, 0xd4, 0x83, 0x98, 0xae, 0x07, 0x32, 0x5d, 0x0f, 0x6a, 0xba, 0x9e,
	0x73, 0x7e, 0x66, 0x9e, 0x13, 0xcb, 0x89, 0x7b, 0xf2, 0x0c, 0x41, 0x08, 0x1d, 0x70, 0xed, 0x4e,
	0xa9, 0x25, 0xc5, 0x12, 0xcc, 0xa4, 0x68, 0x07, 0xe9, 0x10, 0x72, 0xe5, 0xe2, 0x4d, 0x2e, 0x2d,
	0x2a, 0x4a, 0xcd, 0x2b, 0xf1, 0xcd, 0xcc, 0x73, 0x4a, 0x2d, 0x91, 0x60, 0x21, 0xce, 0x08, 0x54,
	0x5d, 0xc8, 0xc6, 0x24, 0x56, 0x80, 0x8c, 0x61, 0x25, 0xd1, 0x18, 0xb0, 0x2e, 0x48, 0x48, 0xb9,
	0x24, 0x96, 0x24, 0x3a, 0xe6, 0xe4, 0x48, 0xb0, 0x29, 0x30, 0x6a, 0x70, 0x06, 0x21, 0x04, 0x9c,
	0xcc, 0x4e, 0x3c, 0x92, 0x63, 0xbc, 0xf0, 0x48, 0x8e, 0xf1, 0xc1, 0x23, 0x39, 0xc6, 0x09, 0x8f,
	0xe5, 0x18, 0x2e, 0x3c, 0x96, 0x63, 0xb8, 0xf1, 0x58, 0x8e, 0x21, 0x4a, 0x06, 0x25, 0x76, 0x2b,
	0xe0, 0xf1, 0x5b, 0x52, 0x59, 0x90, 0x5a, 0x9c, 0xc4, 0x06, 0x8e, 0x12, 0x63, 0x40, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x41, 0x2a, 0xf0, 0xf9, 0x04, 0x02, 0x00, 0x00,
}

func (m *Lottery) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Lottery) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Lottery) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TxDataAll) > 0 {
		i -= len(m.TxDataAll)
		copy(dAtA[i:], m.TxDataAll)
		i = encodeVarintLottery(dAtA, i, uint64(len(m.TxDataAll)))
		i--
		dAtA[i] = 0x32
	}
	{
		size, err := m.CurrentMaxBet.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintLottery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size, err := m.CurrentMinBet.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintLottery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size, err := m.TotalBets.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintLottery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.TotalFees.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintLottery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.TxCounter != 0 {
		i = encodeVarintLottery(dAtA, i, uint64(m.TxCounter))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintLottery(dAtA []byte, offset int, v uint64) int {
	offset -= sovLottery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Lottery) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TxCounter != 0 {
		n += 1 + sovLottery(uint64(m.TxCounter))
	}
	l = m.TotalFees.Size()
	n += 1 + l + sovLottery(uint64(l))
	l = m.TotalBets.Size()
	n += 1 + l + sovLottery(uint64(l))
	l = m.CurrentMinBet.Size()
	n += 1 + l + sovLottery(uint64(l))
	l = m.CurrentMaxBet.Size()
	n += 1 + l + sovLottery(uint64(l))
	l = len(m.TxDataAll)
	if l > 0 {
		n += 1 + l + sovLottery(uint64(l))
	}
	return n
}

func sovLottery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozLottery(x uint64) (n int) {
	return sovLottery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Lottery) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLottery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Lottery: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Lottery: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxCounter", wireType)
			}
			m.TxCounter = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLottery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TxCounter |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalFees", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLottery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLottery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLottery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalFees.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalBets", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLottery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLottery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLottery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalBets.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentMinBet", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLottery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLottery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLottery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CurrentMinBet.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentMaxBet", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLottery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLottery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLottery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CurrentMaxBet.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxDataAll", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLottery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLottery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLottery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxDataAll = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLottery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLottery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipLottery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowLottery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLottery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLottery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthLottery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupLottery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthLottery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthLottery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowLottery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupLottery = fmt.Errorf("proto: unexpected end of group")
)
