version: 1
accounts:
- name: client1
  coins:
  - 500000000token
- name: client2
  coins:
  - 500000000token
- name: client3
  coins:
  - 500000000token
- name: client4
  coins:
  - 500000000token
- name: client5
  coins:
  - 500000000token
- name: client6
  coins:
  - 500000000token
- name: client7
  coins:
  - 500000000token
- name: client8
  coins:
  - 500000000token
- name: client9
  coins:
  - 500000000token
- name: client10
  coins:
  - 500000000token
- name: alice
  coins:
  - 2000000000token
  - 200000000stake
- name: bob
  coins:
  - 10000token
  - 100000000stake
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 5token
  - 100000stake
validators:
- name: alice
  bonded: 100000000stake
