version: 1
accounts:
- name: client1
  coins:
  - 500000000token
- name: client2
  coins:
  - 500000000token
- name: client3
  coins:
  - 500000000token
- name: client4
  coins:
  - 500000000token
- name: client5
  coins:
  - 500000000token
- name: client6
  coins:
  - 500000000token
- name: client7
  coins:
  - 500000000token
- name: client8
  coins:
  - 500000000token
- name: client9
  coins:
  - 500000000token
- name: client10
  coins:
  - 500000000token
- name: client11
  coins:
  - 500000000token
- name: client12
  coins:
  - 500000000token
- name: client13
  coins:
  - 500000000token
- name: client14
  coins:
  - 500000000token
- name: client15
  coins:
  - 500000000token
- name: client16
  coins:
  - 500000000token
- name: client17
  coins:
  - 500000000token
- name: client18
  coins:
  - 500000000token
- name: client19
  coins:
  - 500000000token
- name: client20
  coins:
  - 500000000token
- name: alice
  coins:
  - 2000000000token
  - 200000000stake
- name: bob
  coins:
  - 10000token
  - 100000000stake
faucet:
  name: bob
  coins:
  - 5token
  - 100000stake
client:
  typescript:
    path: ts-client
  openapi:
    path: docs/static/openapi.yml
validators:
- name: alice
  bonded: 100000000stake
  config:
    consensus:
      timeout_commit: 60s
